version: '3.9'

volumes:
  mysql-volume:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./src/:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=caleandar
      - DB_USERNAME=caleandar
      - DB_PASSWORD=caleandar

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 38080:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: caleandar
      MYSQL_USER: caleandar
      MYSQL_PASSWORD: caleandar
      MYSQL_ROOT_PASSWORD: caleandar
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql